// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFAE9t1b83ZwbYw4PsNQsd-A_Mf0A0DYc',
    appId: '1:206211816834:web:a163d51d85ef394505c39b',
    messagingSenderId: '206211816834',
    projectId: 'data-auto-refresh',
    authDomain: 'data-auto-refresh.firebaseapp.com',
    storageBucket: 'data-auto-refresh.appspot.com',
    measurementId: 'G-HM7QZGJRR9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2D6rYwSMnbrc43RPgypFeEegoUA1-E2M',
    appId: '1:206211816834:android:04635c3ec265e9ab05c39b',
    messagingSenderId: '206211816834',
    projectId: 'data-auto-refresh',
    storageBucket: 'data-auto-refresh.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEGF3DgEaGXWiuF3gJt3En8PzqYuVz34w',
    appId: '1:206211816834:ios:d6ee1512a9e004d705c39b',
    messagingSenderId: '206211816834',
    projectId: 'data-auto-refresh',
    storageBucket: 'data-auto-refresh.appspot.com',
    iosClientId: '206211816834-8qn9rcjsqkul715nd403qpil3blbt90p.apps.googleusercontent.com',
    iosBundleId: 'com.example.dataAutoRefresh',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEGF3DgEaGXWiuF3gJt3En8PzqYuVz34w',
    appId: '1:206211816834:ios:d6ee1512a9e004d705c39b',
    messagingSenderId: '206211816834',
    projectId: 'data-auto-refresh',
    storageBucket: 'data-auto-refresh.appspot.com',
    iosClientId: '206211816834-8qn9rcjsqkul715nd403qpil3blbt90p.apps.googleusercontent.com',
    iosBundleId: 'com.example.dataAutoRefresh',
  );
}
